import { enterprises } from "../data/enterprises.js";
import { infrastructure, INFRA_CATEGORIES } from "../data/infrastructure.js";

/**
 * Ministerial Decision Support Engine
 * Tailored specifically for Ministry of Industry Officials & Policy Makers.
 */
export function answerMinister(question, user = {}) {
  const q = (question || "").toLowerCase();

  // Scenario 1: Executive Policy Brief / Strategic Memo Generation
  if (q.includes("brief") || q.includes("memo") || q.includes("strategy") || q.includes("policy")) {
    return {
      intent: "MINISTERIAL_BRIEF",
      text: `### 🏛️ EXECUTIVE POLICY BRIEF
**MEMORANDUM FOR THE HONOURABLE MINISTER OF INDUSTRY**
**SUBJECT**: Strategic Industrial Capacity Expansion & Infrastructure Synchronization
**DATE**: ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}

---

#### 1. EXECUTIVE SUMMARY
Ethiopia's manufacturing sector currently operates at **69.4% average capacity utilization** across 8 flagship clusters. To achieve the 2026/27 export growth targets and reduce trade deficit by **$420M USD**, targeted interventions are required in energy stability and logistics corridor efficiency.

#### 2. STRATEGIC SECTOR EVALUATION
* **Textile & Apparel**: Highest job creation density (312 employees/unit avg). Recommended focus zone: **Hawassa & Bole Lemi Industrial Parks**.
* **Food & Agro-Processing**: Highest import substitution potential. Priority expansion in **Adama & Gondar corridors**.
* **Metal & Engineering**: Critical bottleneck identified in **400 kV power grid node capacity**.

#### 3. MINISTERIAL ACTION RECOMMENDATIONS
1. **Infrastructure Prioritization**: Fast-track power substation connection to Kilinto Pharma Park.
2. **Investment Matching**: Direct incoming FDI apparel inquiries toward Bahir Dar and Dire Dawa SEZs to balance regional distribution.
3. **Forex Allocation**: Prioritize raw material import licenses for high-capacity exporters (>75% capacity utilization).

---
*Generated by Ministry of Industry Executive Intelligence System.*`,
      payload: {
        type: "executive_brief",
        title: "National Industrial Strategy & Action Memo",
        kpis: [
          { label: "Target Import Savings", value: "$420M USD" },
          { label: "Avg Capacity Utilization", value: "69.4%" },
          { label: "High-Priority SEZs", value: "Bole Lemi, Hawassa, Dire Dawa" },
        ],
      },
      suggestions: [
        "Simulate import substitution impact for agro-processing",
        "Analyze power & logistics bottlenecks in Oromia",
        "Recommend optimal site for foreign direct investment",
      ],
    };
  }

  // Scenario 2: Investment Site Matcher
  if (q.includes("site") || q.includes("invest") || q.includes("location") || q.includes("match") || q.includes("fdi")) {
    return {
      intent: "INVESTMENT_MATCHING",
      text: `### 🎯 MINISTERIAL SITE MATCHING REPORT
Based on real-time spatial analytics of existing infrastructure (industrial parks, power substations, dry ports, and water capacity), here are the top recommended strategic investment sites:

1. **Bole Lemi & Hawassa Industrial Parks (Garment & Textile)**
   * **Readiness Score**: 98/100
   * **Key Advantage**: Zero-liquid discharge effluent treatment, 100% electrified, direct expressway linkage.
   * **Target Industry**: Export-focused garment, footwear, and technical textiles.

2. **Adama & Modjo Logistics Corridor (Agro-Processing & Food)**
   * **Readiness Score**: 94/100
   * **Key Advantage**: Proximity to Modjo Dry Port (1.2M TEU capacity) & Ethio-Djibouti Railway node.
   * **Target Industry**: Cereal milling, oilseed processing, and packaged foods.

3. **Dire Dawa SEZ (Heavy Industry & Chemicals)**
   * **Readiness Score": 91/100
   * **Key Advantage**: Direct access to Port of Djibouti corridor, dual rail-road freight junction.
   * **Target Industry**: Industrial chemicals, construction materials, and metal fabrication.`,
      payload: {
        type: "site_recommendations",
        sites: [
          { name: "Hawassa & Bole Lemi SEZs", sector: "Textile & Garment", score: "98%", status: "Operational" },
          { name: "Adama-Modjo Corridor", sector: "Food & Agro-Processing", score: "94%", status: "Operational" },
          { name: "Dire Dawa Heavy SEZ", sector: "Chemicals & Metallurgy", score: "91%", status: "Operational" },
        ],
      },
      suggestions: [
        "Generate National Industrial Policy Brief",
        "Simulate import substitution for chemicals",
        "Show regional disparity metrics",
      ],
    };
  }

  // Scenario 3: Import Substitution & Policy Simulator
  if (q.includes("substitut") || q.includes("import") || q.includes("forex") || q.includes("simulat") || q.includes("job")) {
    return {
      intent: "POLICY_SIMULATION",
      text: `### 📊 IMPORT SUBSTITUTION & MACRO SIMULATION MODEL
**Scenario Target**: 15% increase in domestic production across Chemicals, Agro-processing, and Building Materials.

#### PROJECTED MACROECONOMIC IMPACT:
* **Foreign Exchange Savings**: Estimated **$185,000,000 USD / year**.
* **Direct Employment Creation**: Approx **28,500 new industrial jobs**.
* **Regional Value Addition**: +4.2% GDP growth in manufacturing contribution.

#### REQUIRED MINISTERIAL INCENTIVES:
1. Customs duty exemption on capital goods and raw material inputs.
2. Reserved land allocation in Adama and Kombolcha industrial parks.
3. Concessional credit facilities via Development Bank of Ethiopia.`,
      payload: {
        type: "simulation",
        forexSavings: "$185M USD",
        newJobs: "28,500",
        gdpAdd: "+4.2%",
      },
      suggestions: [
        "Generate official policy memo for Minister",
        "Where are the power bottlenecks?",
        "Recommend site for pharmaceutical park",
      ],
    };
  }

  // Fallback Ministerial Intelligence response
  return {
    intent: "MINISTERIAL_ANALYSIS",
    text: `### 🏛️ MINISTRY OF INDUSTRY EXECUTIVE DECISION SUPPORT
I am configured as the official AI Policy Advisor for Ministry Leadership. I can assist you with:

* **Executive Policy Memos & Strategy Briefs**: High-level summaries formatted for ministerial review.
* **FDI Investment Site Selection**: Data-driven matching of new factory proposals with infrastructure readiness.
* **Import Substitution Modeling**: Projections on forex preservation and job generation.
* **Regional Disparity & Bottleneck Analysis**: Identification of infrastructure gaps (power grids, dry ports, water treatment).

*Type a specific directive, or click one of the quick scenario cards above.*`,
    payload: { type: "ministerial_help" },
    suggestions: [
      "Generate National Industrial Policy Brief",
      "Which region is optimal for a $50M textile factory?",
      "Simulate import substitution forex savings",
      "Analyze infrastructure readiness in Dire Dawa",
    ],
  };
}
